on:
  workflow_call:

permissions:
  security-events: write
  contents: read

jobs:
  secure-iac-dockerfile-scan:
    name: IaC Security - Checkov
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: dockerfile
          output_format: sarif
          output_file_path: checkov-report.sarif
          soft_fail: true

      - name: ğŸ“¤ Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: checkov-report.sarif/results_sarif.sarif
          category: checkov-iac
